'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, useUser } from "@clerk/nextjs";
import Header from "@/component/header";
import Footer from "@/component/footer";
import { Toaster } from "react-hot-toast";
import { useRealtime } from "@/hooks/useRealtime";

// Fonts
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function LayoutContent({ children }: { children: React.ReactNode }) {
    const { user } = useUser();
    const userId = user?.id;

    // ✅ Initialise la connexion socket.io globalement
    useRealtime(userId);

    return (
        <>
            <Header />
            <main className="flex-grow container mx-auto px-4 py-8">
                {children}
            </main>
            <Footer />
            <Toaster position="top-right" />
        </>
    );
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <ClerkProvider>
            <html lang="fr">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gradient-to-r from-indigo-50 via-purple-50 to-pink-50`}
            >
            <LayoutContent>{children}</LayoutContent>
            </body>
            </html>
        </ClerkProvider>
    );
}
