name: Frontend CI

on:
  pull_request:
    paths:
      - 'messagerie-frontend/**'
  push:
    branches:
      - master
    paths:
      - 'messagerie-frontend/**'

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: messagerie-frontend

    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      CLERK_ISSUER: ${{ secrets.CLERK_ISSUER }}
      # (Ajoute ici toutes les autres variables nécessaires, ex: NEXT_PUBLIC_API_URL, etc.)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
